version: "3.7"
services:
  static_site:
    build: .
    volumes:
      - "./src:/usr/share/nginx/html"
      - "./Docker/certs:/etc/ssl"
    ports:
    - "8080:80"
    - "443:443"

  gulp:
    image: ellerbrock/alpine-gulp-sass:latest
    volumes:
      - ${DIR_SASS}:/src/sass
      - ${DIR_CSS}:/src/css
    environment:
      - SASS=${FILES_SASS}
      - CSS=${DIR_CSS}
      - GULP_DEBUG=${GULP_DEBUG}
